services:
  - type: web
    name: blii-pdf-extraction
    env: docker
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PORT
        value: "8080"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn docling_service:app --workers 1 --bind 0.0.0.0:$PORT --timeout 120
