services:
  - type: web
    name: blii-pdf-extraction
    env: docker
    plan: starter
    healthCheckPath: /healthz
    envVars:
      - key: WEB_CONCURRENCY
        value: "1"
      - key: PORT
        value: "8080"
