services:
  - type: web
    name: blii-pdf-extraction
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    plan: starter
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: 1
